<?php

namespace Database\Seeders;

use Illuminate\Support\Facades\DB;
use Illuminate\Database\Seeder;

class VendorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('vendors')->insert([
            [
                'name' => 'Activision',
                'code' => 'ACTIVISION',
                'website' => 'https://www.activision.com',
                'contact_email' => 'support@activision.com',
                'address' => 'Santa Monica, USA',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Bandai Namco',
                'code' => 'BANDAI',
                'website' => 'https://www.bandainamcoent.com',
                'contact_email' => 'support@bandainamco.com',
                'address' => 'Tokyo, Japan',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Bethesda Softworks',
                'code' => 'BETHESDA',
                'website' => 'https://bethesda.net',
                'contact_email' => 'support@bethesda.net',
                'address' => 'Rockville, Maryland, USA',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Capcom',
                'code' => 'CAPCOM',
                'website' => 'https://www.capcom.com',
                'contact_email' => 'support@capcom.com',
                'address' => 'Osaka, Japan',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Com2uS',
                'code' => 'CoM2US',
                'website' => 'https://www.com2us.com',
                'contact_email' => 'support@com2us.com',
                'address' => 'Seoul, South Korea',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Double Fine Productions',
                'code' => 'DOUBLEFINE',
                'website' => 'https://www.doublefine.com',
                'contact_email' => 'support@doublefine.com',
                'address' => 'San Francisco, USA',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Electronic Arts',
                'code' => 'EA',
                'website' => 'https://www.ea.com',
                'contact_email' => 'help@ea.com',
                'address' => 'Redwood City, USA',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Epic Games',
                'code' => 'EPICGAMES',
                'website' => 'https://www.epicgames.com',
                'contact_email' => 'support@epicgames.com',
                'address' => 'Cary, North Carolina, United States',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Garena',
                'code' => 'GARENA',
                'website' => 'https://www.garena.co.id',
                'contact_email' => 'support@garena.com',
                'address' => 'Singapore',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Gameloft',
                'code' => 'GAMELOFT',
                'website' => 'https://www.gameloft.com',
                'contact_email' => 'support@gameloft.com',
                'address' => 'Paris, France',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Gravity',
                'code' => 'GRAVITY',
                'website' => 'https://www.gravity.co.kr',
                'contact_email' => 'support@gravity.co.kr',
                'address' => 'Seoul, South Korea',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'GTarcade (Yoozoo Games)',
                'code' => 'GTARCADE',
                'website' => 'https://www.gtarcade.com',
                'contact_email' => 'support@gtarcade.com',
                'address' => 'Shanghai, China',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'IGG',
                'code' => 'IGG',
                'website' => 'https://www.igg.com',
                'contact_email' => 'support@igg.com',
                'address' => 'Singapore',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'HoYoverse',
                'code' => 'HOYOVERSE',
                'website' => 'https://www.hoyoverse.com',
                'contact_email' => 'support@hoyoverse.com',
                'address' => 'Shanghai, China',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Innersloth',
                'code' => 'INNERSLOTH',
                'website' => 'https://www.innersloth.com',
                'contact_email' => 'support@innersloth.com',
                'address' => 'Redmond, Washington, United States',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Konami',
                'code' => 'KONAMI',
                'website' => 'https://www.konami.com',
                'contact_email' => 'support@konami.com',
                'address' => 'Tokyo, Japan',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Krafton',
                'code' => 'KRAFTON',
                'website' => 'https://www.krafton.com',
                'contact_email' => 'support@krafton.com',
                'address' => 'Seoul, South Korea',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Level Infinite',
                'code' => 'LEVELINFINITE',
                'website' => 'https://www.levelinfinite.com',
                'contact_email' => 'support@levelinfinite.com',
                'address' => 'Singapore',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Lilith Games',
                'code' => 'LILITH',
                'website' => 'https://www.lilithgames.com',
                'contact_email' => 'support@lilithgames.com',
                'address' => 'Shanghai, China',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'miHoYo',
                'code' => 'MIHOYO',
                'website' => 'https://www.mihoyo.com',
                'contact_email' => 'support@mihoyo.com',
                'address' => 'Shanghai, China',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Moonton',
                'code' => 'MOONTON',
                'website' => 'https://www.moonton.com',
                'contact_email' => 'support@moonton.com',
                'address' => 'Shanghai, China',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'NetEase Games',
                'code' => 'NETEASE',
                'website' => 'https://www.neteasegames.com',
                'contact_email' => 'support@neteasegames.com',
                'address' => 'Hangzhou, China',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Netmarble',
                'code' => 'NETMARBLE',
                'website' => 'https://www.netmarble.com',
                'contact_email' => 'support@netmarble.com',
                'address' => 'Seoul, South Korea',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Nexon',
                'code' => 'NEXON',
                'website' => 'https://www.nexon.com',
                'contact_email' => 'support@nexon.com',
                'address' => 'Seoul, South Korea',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Niantic',
                'code' => 'NIANTIC',
                'website' => 'https://nianticlabs.com',
                'contact_email' => 'support@nianticlabs.com',
                'address' => 'San Francisco, USA',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Riot Games',
                'code' => 'RIOTGAMES',
                'website' => 'https://www.riotgames.com',
                'contact_email' => 'support@riotgames.com',
                'address' => 'Los Angeles, USA',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Roblox Corporation',
                'code' => 'ROBLOX',
                'website' => 'https://www.roblox.com',
                'contact_email' => 'info@roblox.com',
                'address' => 'San Mateo, California, USA',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Rockstar Games',
                'code' => 'ROCKSTAR',
                'website' => 'https://www.rockstargames.com',
                'contact_email' => 'support@rockstargames.com',
                'address' => 'New York, USA',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'SEGA',
                'code' => 'SEGA',
                'website' => 'https://www.sega.com',
                'contact_email' => 'support@sega.com',
                'address' => 'Tokyo, Japan',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sony Interactive Entertainment',
                'code' => 'SONY',
                'website' => 'https://www.playstation.com',
                'contact_email' => 'support@sony.com',
                'address' => 'Tokyo, Japan',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Square Enix',
                'code' => 'SQUARENIX',
                'website' => 'https://www.square-enix.com',
                'contact_email' => 'support@square-enix.com',
                'address' => 'Tokyo, Japan',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Supercell',
                'code' => 'SUPPERCELL',
                'website' => 'https://supercell.com',
                'contact_email' => 'support@supercell.com',
                'address' => 'Helsinki, Finland',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tencent Games',
                'code' => 'TENCENT',
                'website' => 'https://www.tencent.com',
                'contact_email' => 'support@tencentgames.com',
                'address' => 'Shenzhen, China',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ubisoft',
                'code' => 'UBISOFT',
                'website' => 'https://www.ubisoft.com',
                'contact_email' => 'support@ubisoft.com',
                'address' => 'Montreuil, France',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Wargaming.net',
                'code' => 'WARGAMING',
                'website' => 'https://www.wargaming.net',
                'contact_email' => 'support@wargaming.net',
                'address' => 'Nicosia, Cyprus',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Zepetto',
                'code' => 'ZEPETTO',
                'website' => 'https://www.zepetto.com',
                'contact_email' => 'support@zepetto.com',
                'address' => 'Seoul, South Korea',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Zynga',
                'code' => 'ZYNGA',
                'website' => 'https://www.zynga.com',
                'contact_email' => 'support@zynga.com',
                'address' => 'San Francisco, USA',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
